// lib/mockData.js

export const mockUsers = [
  {
    id: "1",
    avatar: "/logo.png",
    username: "Rohit Sharma",
    joinDate: "2025-01-15",
    role: "Admin",
    status: "online",
  },
  {
    id: "2",
    avatar: "/logo.png",
    username: "KL Rahul",
    joinDate: "2025-02-20",
    role: "Member",
    status: "offline",
  },
  {
    id: "3",
    avatar: "/logo.png",
    username: "Hardik",
    joinDate: "2025-03-10",
    role: "Moderator",
    status: "online",
  },
  {
    id: "4",
    avatar: "/logo.png",
    username: "Virat Kohli",
    joinDate: "2025-04-05",
    role: "Member",
    status: "idle",
  },
  {
    id: "5",
    avatar: "/logo.png",
    username: "Nitish Reddy",
    joinDate: "2025-05-12",
    role: "Member",
    status: "dnd",
  },
  {
    id: "6",
    avatar: "/logo.png",
    username: "R Jadeja",
    joinDate: "2025-06-01",
    role: "Member",
    status: "online",
  },
  {
    id: "7",
    avatar: "/logo.png",
    username: "Y Jaiswal",
    joinDate: "2025-07-19",
    role: "Member",
    status: "offline",
  },
  {
    id: "8",
    avatar: "/logo.png",
    username: "S Gill",
    joinDate: "2025-08-25",
    role: "Member",
    status: "online",
  },
  {
    id: "9",
    avatar: "/logo.png",
    username: "Surya K Yadav",
    joinDate: "2025-09-03",
    role: "Member",
    status: "idle",
  },
  {
    id: "10",
    avatar: "/logo.png",
    username: "R Pant",
    joinDate: "2025-10-11",
    role: "Member",
    status: "dnd",
  },
  {
    id: "11",
    avatar: "/logo.png",
    username: "B Singh",
    joinDate: "2025-11-07",
    role: "Member",
    status: "online",
  },
  {
    id: "12",
    avatar: "/logo.png",
    username: "B Kumar",
    joinDate: "2025-12-14",
    role: "Member",
    status: "offline",
  },
  {
    id: "13",
    avatar: "/logo.png",
    username: "Shreyas Iyer",
    joinDate: "2025-01-22",
    role: "Member",
    status: "online",
  },
  {
    id: "14",
    avatar: "/logo.png",
    username: "Kumar",
    joinDate: "2025-02-29",
    role: "Member",
    status: "idle",
  },
  {
    id: "15",
    avatar: "/logo.png",
    username: "Rinku Singh",
    joinDate: "2025-03-18",
    role: "Member",
    status: "dnd",
  },
]

export const mockRoles = [
  { id: "r1", name: "Admin", color: "#F04747", enabled: true },
  { id: "r2", name: "Moderator", color: "#43B581", enabled: true },
  { id: "r3", name: "Member", color: "#7289DA", enabled: true },
  { id: "r4", name: "Bot", color: "#99AAB5", enabled: false },
  { id: "r5", name: "Guest", color: "#FAA61A", enabled: true },
]

export const mockMessages = [
  {
    id: "m1",
    avatar: "/logo.png",
    username: "Rohit Sharma",
    timestamp: "2024-06-25T10:00:00Z",
    content: "Hello everyone! Welcome to the server.",
  },
  {
    id: "m2",
    avatar: "/logo.png",
    username: "KL Rahul",
    timestamp: "2024-06-25T10:05:00Z",
    content: "Thank you, Cap! Glad to be here.",
  },
  {
    id: "m3",
    avatar: "/logo.png",
    username: "Hardik",
    timestamp: "2024-06-25T10:15:00Z",
    content: "Please check out the rules channel.",
  },
  {
    id: "m4",
    avatar: "/logo.png",
    username: "Virat Kohli",
    timestamp: "2024-06-25T10:20:00Z",
    content: "Is anyone online for a quick game?",
  },
  {
    id: "m5",
    avatar: "/logo.png",
    username: "Nitish Reddy",
    timestamp: "2024-06-25T10:30:00Z",
    content: "Yes, I am! What's up?",
  },
  {
    id: "m6",
    avatar: "/logo.png",
    username: "R Jadeja",
    timestamp: "2024-06-25T10:45:00Z",
    content: "Just joined, looking forward to interacting!",
  },
  {
    id: "m7",
    avatar: "/logo.png",
    username: "Y Jaiswal",
    timestamp: "2024-06-25T11:00:00Z",
    content: "Welcome, Bhai!",
  },
  {
    id: "m8",
    avatar: "/logo.png",
    username: "S Gill",
    timestamp: "2024-06-25T11:10:00Z",
    content: "Good Game, everyone!",
  },
  {
    id: "m9",
    avatar: "/logo.png",
    username: "Surya K Yadav",
    timestamp: "2024-06-25T11:20:00Z",
    content: "Morning Captain!",
  },
  {
    id: "m10",
    avatar: "/logo.png",
    username: "R Pant",
    timestamp: "2024-06-25T11:30:00Z",
    content: "Any new announcements?",
  },
]

export const mockChartData = [
  { month: "Jan", members: 100 },
  { month: "Feb", members: 120 },
  { month: "Mar", members: 150 },
  { month: "Apr", members: 130 },
  { month: "May", members: 180 },
  { month: "Jun", members: 200 },
]

export const mockMetrics = {
  totalMembers: mockUsers.length,
  onlineUsers: mockUsers.filter((user) => user.status === "online").length,
  activeRoles: mockRoles.filter((role) => role.enabled).length,
  messagesToday: mockMessages.length,
}
