// lib/mockData.js

export const mockUsers = [
  {
    id: "1",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Priya Sharma",
    joinDate: "2023-01-15",
    role: "Admin",
    status: "online",
  },
  {
    id: "2",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Rahul Singh",
    joinDate: "2023-02-20",
    role: "Member",
    status: "offline",
  },
  {
    id: "3",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Anjali Devi",
    joinDate: "2023-03-10",
    role: "Moderator",
    status: "online",
  },
  {
    id: "4",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Vikram Kumar",
    joinDate: "2023-04-05",
    role: "Member",
    status: "idle",
  },
  {
    id: "5",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Sneha Reddy",
    joinDate: "2023-05-12",
    role: "Member",
    status: "dnd",
  },
  {
    id: "6",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Arjun Patel",
    joinDate: "2023-06-01",
    role: "Member",
    status: "online",
  },
  {
    id: "7",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Kavita Rao",
    joinDate: "2023-07-19",
    role: "Member",
    status: "offline",
  },
  {
    id: "8",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Siddharth Gupta",
    joinDate: "2023-08-25",
    role: "Member",
    status: "online",
  },
  {
    id: "9",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Meera Joshi",
    joinDate: "2023-09-03",
    role: "Member",
    status: "idle",
  },
  {
    id: "10",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Rohan Verma",
    joinDate: "2023-10-11",
    role: "Member",
    status: "dnd",
  },
  {
    id: "11",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Divya Singh",
    joinDate: "2023-11-07",
    role: "Member",
    status: "online",
  },
  {
    id: "12",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Amit Sharma",
    joinDate: "2023-12-14",
    role: "Member",
    status: "offline",
  },
  {
    id: "13",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Neha Kumari",
    joinDate: "2024-01-22",
    role: "Member",
    status: "online",
  },
  {
    id: "14",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Rajesh Kumar",
    joinDate: "2024-02-29",
    role: "Member",
    status: "idle",
  },
  {
    id: "15",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Pooja Singh",
    joinDate: "2024-03-18",
    role: "Member",
    status: "dnd",
  },
]

export const mockRoles = [
  { id: "r1", name: "Admin", color: "#F04747", enabled: true },
  { id: "r2", name: "Moderator", color: "#43B581", enabled: true },
  { id: "r3", name: "Member", color: "#7289DA", enabled: true },
  { id: "r4", name: "Bot", color: "#99AAB5", enabled: false },
  { id: "r5", name: "Guest", color: "#FAA61A", enabled: true },
]

export const mockMessages = [
  {
    id: "m1",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Priya Sharma",
    timestamp: "2024-06-25T10:00:00Z",
    content: "Namaste everyone! Welcome to the server.",
  },
  {
    id: "m2",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Rahul Singh",
    timestamp: "2024-06-25T10:05:00Z",
    content: "Dhanyawad, Priya! Glad to be here.",
  },
  {
    id: "m3",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Anjali Devi",
    timestamp: "2024-06-25T10:15:00Z",
    content: "Please check out the #n नियम (rules) channel.",
  },
  {
    id: "m4",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Vikram Kumar",
    timestamp: "2024-06-25T10:20:00Z",
    content: "Is anyone online for a quick chat?",
  },
  {
    id: "m5",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Sneha Reddy",
    timestamp: "2024-06-25T10:30:00Z",
    content: "Yes, I am! What's up?",
  },
  {
    id: "m6",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Arjun Patel",
    timestamp: "2024-06-25T10:45:00Z",
    content: "Just joined, looking forward to interacting!",
  },
  {
    id: "m7",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Kavita Rao",
    timestamp: "2024-06-25T11:00:00Z",
    content: "Welcome, Arjun!",
  },
  {
    id: "m8",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Siddharth Gupta",
    timestamp: "2024-06-25T11:10:00Z",
    content: "Shubh Prabhat, everyone!",
  },
  {
    id: "m9",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Meera Joshi",
    timestamp: "2024-06-25T11:20:00Z",
    content: "Morning Siddharth!",
  },
  {
    id: "m10",
    avatar: "/placeholder.svg?height=40&width=40",
    username: "Rohan Verma",
    timestamp: "2024-06-25T11:30:00Z",
    content: "Any new announcements?",
  },
]

export const mockChartData = [
  { month: "Jan", members: 100 },
  { month: "Feb", members: 120 },
  { month: "Mar", members: 150 },
  { month: "Apr", members: 130 },
  { month: "May", members: 180 },
  { month: "Jun", members: 200 },
]

export const mockMetrics = {
  totalMembers: mockUsers.length,
  onlineUsers: mockUsers.filter((user) => user.status === "online").length,
  activeRoles: mockRoles.filter((role) => role.enabled).length,
  messagesToday: mockMessages.length,
}
